public enum TrackType {
    SINGLE_STRIGHT,
    DOUBLE_STRIGHT,
    SINGLE_CURVE, 
    DOUBLE_CURVE, 
    LEFT_HAND_POINT, 
    RIGHT_HAND_POINT, 
    LEFT_HAND_CROSSOVER, 
    RIGHT_HAND_CROSSOVER
}

